### ISSUE TITLE
Notice: Undefined variable: title_text 

### ISSUE THREAD

**Issue by raortegar** [andstenberg-rs/moodle-block_readspeaker_embhl#6]
Hi!
I get a notice of undefined variable: 
https://github.com/andstenberg-rs/moodle-readspeaker_embhl/blob/a59945a9654f9372f776ed9332e7e31ea4104e20/block_readspeaker_embhl.php#L135

The variable $title_text should be change for $listen_text

Thanks a lot!

**Comment by Kayyin** [comment]
This is now fixed with push 919137d175202a68a98bc312afd717b0ae514479.
