### ISSUE TITLE
wrong installation location - correct blocks/readspeaker_embhl

### ISSUE THREAD

**Issue by peta3000** [andstenberg-rs/moodle-block_readspeaker_embhl#7]
Hi, 
the Moodle expected installation location and folder-naming is:

blocks/readspeaker_embhl (even if our login is blocks_readspeaker_embhl)

not

blocks/blocks_readspeaker_embhl

checkout https://docs.moodle.org/dev/Blocks#Ready.2C_Set.2C_Go.21

or other examples

Installed in blocks/blocks_readspeaker_embhl (at least as submodule) Moodle will abort installation

**Comment by Kayyin** [comment]
@peta3000 
Thanks for the notice of the typo! This is now fixed with push 2c2d133e8ea7fdcda13108b8b626763ed2d052f1.
