### ISSUE TITLE
Update github repository

### ISSUE THREAD

**Issue by durzo** [andstenberg-rs/moodle-block_readspeaker_embhl#9]
The latest release on https://moodle.org/plugins/block_readspeaker_embhl was on April 18 2024 with plugin version 2024041801 but this github repo has not been updated in some time.

can you please push the latest plugin code to this repository?

**Comment by Kayyin** [comment]
Apologies for the delay on this, we've been working on a new update and took the opportunity to update the code with these changes as well. The changes are now available for the December minor release (20241216).
